import React from 'react';
export default function Portfolio() {
return (
  <div>
    <div className="galeriePoze">
      <img
        src="https://placehold.co/600x400"
        alt=""
      />
      <img
        src="https://placehold.co/600x400"
        alt=""
      />
      <img
        src="https://placehold.co/600x400"
        alt=""
      />
      <img
        src="https://placehold.co/600x400"
        alt=""
      />
      <img
        src="https://placehold.co/600x400"
        alt=""
      />
      <img
        src="https://placehold.co/600x400"
        alt=""
      />
      <img
        src="https://placehold.co/600x400"
        alt=""
      />
      <img
        src="https://placehold.co/600x400"
        alt=""
      />
      <img
        src="https://placehold.co/600x400"
        alt=""
      />
      <img
        src="https://placehold.co/600x400"
        alt=""
      />
      <img
        src="https://placehold.co/600x400"
        alt=""
      />
      <img
        src="https://placehold.co/600x400"
        alt=""
      />
    </div>
    <button>sus</button>
  </div>
);
}
